version: "3.7"
networks:
  default:
    name: zerofeerouting_network
    ipam:
      driver: default
      config:
        - subnet: "10.21.21.0/24"
services:
  postgres-cln:
    container_name: postgres-cln
    image: postgres:14.12@sha256:f5e7b2f87ec217f44490f35d83cc97c1ab3748e88b641dbf87d16b8b99a46edd
    environment:
      POSTGRES_USER: ${CLN_POSTGRES_USER}
      POSTGRES_DB: ${CLN_POSTGRES_DB}
      POSTGRES_PASSWORD: ${CLN_POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - ./data/cln/postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: "10.21.21.98"
  cln:
    container_name: cln
    image: elementsproject/lightningd:v24.02-amd64@sha256:0dd9aa8a59e50f5acd17de27785f1b27b3ceb05c8aa17dd8dda8d751e66728b3
    command:
      - --conf=/config/lightning/conf
      - --alias=${CLN_ALIAS} 
      - --addr=0.0.0.0:9735 
      - --wallet=postgres://${CLN_POSTGRES_USER}:${CLN_POSTGRES_PASSWORD}@postgres-cln:5432/${CLN_POSTGRES_DB}
      - --bitcoin-rpcuser=${BITCOIN_RPCUSER}
      - --bitcoin-rpcpassword=${BITCOIN_RPCPASSWORD}
      - --bitcoin-rpcconnect=${BITCOIN_RPCCONNECT}
      - --bitcoin-rpcport=${BITCOIN_RPCPORT}
    environment:
      EXPOSE_TCP: "TRUE"
    ports:
      - "9735:9735"
    restart: unless-stopped
    volumes:
      - ./config/cln:/config/lightning
      - ./data/cln/lightning:/root/.lightning
    links: 
      - postgres-cln
    networks:
      default:
        ipv4_address: "10.21.21.100"

